### ISSUE TITLE
TODO: Strict mode

### ISSUE THREAD

**Issue by wfjsw** [wfjsw/Stepladder-Bleeding#1]
Strict Mode is used to provide additional security protect for both client and server. 
Strict Mode should be easily turned either on or off in the config file.

It should provide following function: 

- [ ] Denied Access to local address (security threat) (should be on by default)
- [ ] Denied Access to China address (An IP-List should be there, protecting server against backdoor)
- [ ] Client certificate authorization should be used? (Like SSH public key auth)
- [ ] Maybe stronger cipher, more than a gob and tls.
- [ ] A little obfuscation (I am looking forward to obfsproxy :smiley: )

**Comment by wfjsw** [comment]
Alright, may be TLS is already an obfuscation, 
but I am afraid of the DPI.

**Comment by wfjsw** [comment]
An All-to-tcp  implement will be applied to wfjsw/godns
